<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Home" name="Demo.NewtoursMultipleCheck" tests="6" failures="1" timestamp="28 May 2016 02:02:38 GMT" time="20.063" errors="0">
  <testcase name="verifySupportTitle" time="3.385" classname="Demo.NewtoursMultipleCheck"/>
  <testcase name="verifyRegisterTitle" time="2.186" classname="Demo.NewtoursMultipleCheck"/>
  <testcase name="verifySupportTitle" time="4.910" classname="Demo.NewtoursMultipleCheck"/>
  <testcase name="verifySupportTitle" time="3.447" classname="Demo.NewtoursMultipleCheck"/>
  <testcase name="verifyRegisterTitle" time="2.750" classname="Demo.NewtoursMultipleCheck"/>
  <testcase name="verifyRegisterTitle" time="3.385" classname="Demo.NewtoursMultipleCheck">
    <failure type="java.lang.AssertionError" message="expected [Register: Mercury Tours] but found [Welcome: Mercury Tours]">
      <![CDATA[java.lang.AssertionError: expected [Register: Mercury Tours] but found [Welcome: Mercury Tours]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at Demo.NewtoursMultipleCheck.verifyRegisterTitle(NewtoursMultipleCheck.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifyRegisterTitle -->
</testsuite> <!-- Demo.NewtoursMultipleCheck -->
